# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: flexwork
services:
  back-end:
    image: theflexwork/flexwork-server:latest
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/flexwork
      - SPRING_DATASOURCE_USERNAME=flexwork
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      - postgresql
    env_file:
      - ./.backend.env
  front-end:
    image: theflexwork/flexwork-frontend:latest
    environment:
      - AUTH_TRUST_HOST=true
      - BACK_END_SERVER=http://back-end:8080
    ports:
      - '3000:3000'
    env_file:
      - ./.frontend.env
  postgresql:
    image: postgres:16.3
    volumes:
      - ./volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=flexwork
      - POSTGRES_USER=flexwork
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certificate-authority:/data/caddy/pki/authorities/local
    ports:
      - '443:443'
    extra_hosts:
      - "front-end:host-gateway"
